packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@emotion/react": 11.13.3
  "@mantine/carousel": 7.13.4
  "@mantine/charts": 7.13.4
  "@mantine/code-highlight": 7.13.4
  "@mantine/core": 7.13.4
  "@mantine/dates": 7.13.4
  "@mantine/dropzone": 7.13.4
  "@mantine/form": 7.13.4
  "@mantine/hooks": 7.13.4
  "@mantine/modals": 7.13.4
  "@mantine/notifications": 7.13.4
  "@mantine/nprogress": 7.13.4
  "@mantine/spotlight": 7.13.4
  "@mantine/tiptap": 7.13.4
  "@supabase/ssr": 0.5.1
  "@supabase/supabase-js": 2.46.1
  "@t3-oss/env-nextjs": 0.11.1
  "@tabler/icons-react": 3.21.0
  "@tanstack/react-query": 5.59.16
  "@tiptap/extension-link": 2.9.1
  "@tiptap/react": 2.9.1
  "@tiptap/starter-kit": 2.9.1
  "@trpc/client": 11.0.0-rc.477
  "@trpc/react-query": 11.0.0-rc.477
  "@trpc/server": 11.0.0-rc.477
  "@types/node": 22.8.4
  "@types/react": 18.3.12
  "@types/react-dom": 18.3.1
  "@types/uuid": 10.0.0
  dayjs: 1.11.13
  dotenv-cli: 7.4.2
  embla-carousel-react: 8.3.1
  eslint: 9.13.0
  inngest: 3.25.0
  jiti: 2.3.3
  mantine-form-zod-resolver: 1.1.0
  mantine-react-table: 2.0.0-beta.0
  moment: 2.30.1
  next: 15.0.2
  prettier: 3.3.3
  react: 19.0.0-rc-6cf85185-20241014
  react-dom: 19.0.0-rc-6cf85185-20241014
  recharts: 2.13.1
  superjson: 2.2.1
  postcss: 8.4.47
  postcss-preset-mantine: 1.17.0
  postcss-simple-vars: 7.0.1
  posthog-js: 1.178.0
  typescript: 5.6.3
  uuid: 11.0.2
  zod: 3.23.8
  zustand: 5.0.1
